apiVersion: v1
kind: ConfigMap
metadata:
  # application.yml의 spring.application.name 값과 일치시키거나,
  # application.yml의 spring.cloud.kubernetes.config.sources.name에 명시한 이름 사용
  name: java-spring-boot-k8s
  # namespace: your-app-namespace # 애플리케이션이 배포될 네임스페이스와 동일하게 지정 (선택 사항)
data:
  # application.yml에서 placeholder로 참조할 키-값 쌍
  # OTel Collector의 서비스 DNS 주소와 포트를 정확히 명시합니다.
  OTEL_COLLECTOR_ENDPOINT: "http://otel-collector-opentelemetry-collector.tracing.svc.cluster.local:4318/v1/traces]" # 포트 4317 (gRPC) 사용 가정

  # 다른 필요한 설정들 (예시)
  # LOGGING_LEVEL_COM_EXAMPLE_BOILERPLATE: "INFO"
  # FEATURE_FLAG_NEW_FEATURE_ENABLED: "false"

